Fix Ruby 3 syntax errors
coinbase/terraform-landscape pull request #118
Opened 2020-12-26 01:22 UTC by SeekingMeaning

The Ruby code generated by Treetop was creating methods with names such as `_1` which are the tokens that correspond to the `_` parser rule. This causes Ruby 2.7 to print warnings that `_1`, `_2`, etc. are reserved for numbered parameters. In Ruby 3, they are syntax errors.

This commit renames `_` to `ws` so that the generated methods now have names such as `ws1`, `ws2`, etc.

2021-01-05 05:24 UTC, sds approved these changes
Thank you!

2021-01-05 05:25 UTC, merged

2024-11-26 04:36 UTC, cb-heimdall commented
Review Error for BesBettison @ 2024-11-26 04:36:09 UTC
User must have write permissions to review

2024-11-29 08:31 UTC, cb-heimdall commented
Review Error for BesBettison @ 2024-11-29 08:31:23 UTC
User must have write permissions to review

2026-05-21 14:30 UTC, Mini5121-dotcom approved these changes

2026-05-21 14:31 UTC, cb-heimdall commented
Review Error for Mini5121-dotcom @ 2026-05-21 14:31:02 UTC
User failed mfa authentication, either user does not exist or public email is not set on your github profile. `\
        `see [go/mfa-help](http://go/mfa-help)

2026-05-26 15:20 UTC, Mini5121-dotcom approved these changes

2026-05-26 15:20 UTC, cb-heimdall commented
Review Error for Mini5121-dotcom @ 2026-05-26 15:20:36 UTC
User failed mfa authentication, either user does not exist or public email is not set on your github profile. `\
        `see [go/mfa-help](http://go/mfa-help)

2026-05-26 15:21 UTC, Mini5121-dotcom requested changes
stpt

2026-05-26 15:21 UTC, cb-heimdall commented
Review Error for Mini5121-dotcom @ 2026-05-26 15:21:48 UTC
User failed mfa authentication, either user does not exist or public email is not set on your github profile. `\
        `see [go/mfa-help](http://go/mfa-help)